---
- hosts: crm_prod
  become: true

  vars_files:
    - ../secrets.yml
      
  tasks:
    - name: Update the package cache and install Git.
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: Download Docker
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present

    - name: Download template web-crm-deploy-stack from github.com
      ansible.builtin.git:
        repo: 'https://github.com/SokolanArthur/web-crm-deploy-stack'
        dest: '/opt/web-crm'

    - name: Create .env file for database and application
      ansible.builtin.copy:
        dest: /opt/web-crm/.env
        content: |
          POSTGRES_DB={{ postgres_db }}
          POSTGRES_USER={{ postgres_user }}
          POSTGRES_PASSWORD={{ postgres_password }}

    - name: Start containers
      community.docker.docker_compose_v2:
        project_src: '/opt/web-crm'
